name: color_picker
version: 1.3.0
authors:
- Ali Akbar Vathi <ali.akbar@gmail.com>
- Hadrien Lejard <hadrien.lejard@gmail.com>
description: The Color Picker control creates a Adobe Photoshop style HSV color picker  where the RGB values can be picked based on the Hue, Saturation and Value  parameters.  Multiple sizes are supported.
homepage: https://github.com/coderespawn/dart-color-picker

environment:
  sdk: '>=1.24.0 <3.0.0'

dev_dependencies:
  test: ^1.3.0
  build: '>=0.11.1 <1.0.0'
  build_runner: '>=0.8.0 <1.0.0'
  build_web_compilers: '>=0.4.0 <1.0.0'
